<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE program [
  <!ELEMENT program (tac+)>
  <!ELEMENT tac (dst?,src1?,src2?)>
  <!ELEMENT dst (#PCDATA)>
  <!ELEMENT src1 (#PCDATA)>
  <!ELEMENT src2 (#PCDATA)>
  <!ATTLIST program name CDATA #IMPLIED>
  <!ATTLIST tac opcode CDATA #REQUIRED>
  <!ATTLIST tac order CDATA #REQUIRED>
  <!ATTLIST dst type (integer|string|variable|label) #REQUIRED>
  <!ATTLIST src1 type (integer|string|variable) #REQUIRED>
  <!ATTLIST src2 type (integer|string|variable) #REQUIRED>
  <!ENTITY language "IPPeCode">
  <!ENTITY eol "&#xA;">
  <!ENTITY lt "&lt;">
  <!ENTITY gt "&gt;">
]>
<program name="&language; Program">
  <tac opcode="READINT" order="1">
    <dst type="variable">y</dst>
  </tac>
  <tac opcode="ADD" order="2">
    <dst type="variable">x1</dst>
    <src1 type="variable">y</src1>
    <src2 type="integer">10</src2>
  </tac>
  <tac opcode="PRINT" order="3">
    <dst type="string">Hello&amp;eol;World!</dst>
  </tac>
  <tac opcode="PRINT" order="4">
    <dst type="variable">x1</dst>
  </tac>
  <tac opcode="PRINT" order="5">
    <dst type="string">&amp;eol;</dst>
  </tac>
</program>
